language: scala
scala:
    - 2.11.4
jdk:
    - oraclejdk7
branches:
    only:
        - master
        - develop
        - /^release/.*$/
notifications:
  irc:
    channels:
      - "irc.esper.nett#ModScript"